"""add bonus_spins to members

Revision ID: 0d54f34e4300
Revises: 5f00c9c8ea04
Create Date: 2026-09-14 17:08:47.499916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d54f34e4300'
down_revision = '5f00c9c8ea04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('bonus_spins', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'bonus_spins')
    # ### end Alembic commands ###
