"""add double xp window to app_settings

Revision ID: 12e78268bbf8
Revises: 1ad15e134109
Create Date: 2026-09-14 03:40:39.654706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e78268bbf8'
down_revision = '1ad15e134109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('double_xp_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('app_settings', sa.Column('double_xp_end', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'double_xp_end')
    op.drop_column('app_settings', 'double_xp_start')
    # ### end Alembic commands ###
