"""add backups_enabled to app_settings

Revision ID: 1ad15e134109
Revises: 9874e76d1861
Create Date: 2026-09-13 15:56:15.398480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad15e134109'
down_revision = '9874e76d1861'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('backups_enabled', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'backups_enabled')
    # ### end Alembic commands ###
