"""add index on members points_balance

Revision ID: 5bf1e01e85f7
Revises: 8afafe8b98c3
Create Date: 2026-09-13 01:13:49.786961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bf1e01e85f7'
down_revision = '8afafe8b98c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_members_points_balance'), 'members', ['points_balance'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_points_balance'), table_name='members')
    # ### end Alembic commands ###
