"""add wheel spin tracking

Revision ID: 5f00c9c8ea04
Revises: 72bd440ac185
Create Date: 2026-09-14 16:59:37.662195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f00c9c8ea04'
down_revision = '72bd440ac185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wheel_spins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('prize_label', sa.String(), nullable=False),
    sa.Column('xp_awarded', sa.Integer(), nullable=False),
    sa.Column('spun_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wheel_spins_member_id'), 'wheel_spins', ['member_id'], unique=False)
    op.add_column('members', sa.Column('last_spin_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'last_spin_date')
    op.drop_index(op.f('ix_wheel_spins_member_id'), table_name='wheel_spins')
    op.drop_table('wheel_spins')
    # ### end Alembic commands ###
