"""add custom_badges table

Revision ID: 6cabfa763ddf
Revises: 0d54f34e4300
Create Date: 2026-09-14 20:10:36.840783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cabfa763ddf'
down_revision = '0d54f34e4300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'threshold', name='uq_custom_badge_category_threshold')
    )
    op.create_index(op.f('ix_custom_badges_category'), 'custom_badges', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custom_badges_category'), table_name='custom_badges')
    op.drop_table('custom_badges')
    # ### end Alembic commands ###
