"""add member_badges table

Revision ID: 6d687e43f8df
Revises: d21d79246ce7
Create Date: 2026-09-12 04:15:26.415858

"""
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa

from app.badges import ATTENDANCE_BADGES, STREAK_BADGES


# revision identifiers, used by Alembic.
revision = '6d687e43f8df'
down_revision = 'd21d79246ce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('badge_type', sa.String(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'badge_type', 'threshold', name='uq_member_badge')
    )
    op.create_index(op.f('ix_member_badges_member_id'), 'member_badges', ['member_id'], unique=False)
    # ### end Alembic commands ###

    # Backfill: badges existing members already qualify for under current stats.
    # earned_at can't be recovered exactly (we don't know when the threshold was actually
    # crossed historically), so it's set to "now" as the best available approximation.
    bind = op.get_bind()
    now = datetime.now(timezone.utc)

    members = bind.execute(sa.text("SELECT id, longest_streak FROM members")).fetchall()
    for member_id, longest_streak in members:
        total_visits = bind.execute(
            sa.text("SELECT COUNT(*) FROM visits WHERE member_id = :mid"), {"mid": member_id}
        ).scalar()

        for threshold, name in ATTENDANCE_BADGES:
            if total_visits >= threshold:
                bind.execute(
                    sa.text(
                        "INSERT INTO member_badges (member_id, badge_type, threshold, name, earned_at) "
                        "VALUES (:mid, 'attendance', :threshold, :name, :earned_at)"
                    ),
                    {"mid": member_id, "threshold": threshold, "name": name, "earned_at": now},
                )

        for threshold, name in STREAK_BADGES:
            if longest_streak >= threshold:
                bind.execute(
                    sa.text(
                        "INSERT INTO member_badges (member_id, badge_type, threshold, name, earned_at) "
                        "VALUES (:mid, 'streak', :threshold, :name, :earned_at)"
                    ),
                    {"mid": member_id, "threshold": threshold, "name": name, "earned_at": now},
                )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_badges_member_id'), table_name='member_badges')
    op.drop_table('member_badges')
    # ### end Alembic commands ###
