"""add discord_username to members

Revision ID: 72bd440ac185
Revises: 12e78268bbf8
Create Date: 2026-09-14 04:59:26.734330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72bd440ac185'
down_revision = '12e78268bbf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('discord_username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'discord_username')
    # ### end Alembic commands ###
