"""add weekly streak tracking

Revision ID: 8afafe8b98c3
Revises: 6d687e43f8df
Create Date: 2026-09-12 05:34:07.441419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8afafe8b98c3'
down_revision = '6d687e43f8df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('current_weekly_streak', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('members', sa.Column('longest_weekly_streak', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('members', sa.Column('last_check_in_week', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'last_check_in_week')
    op.drop_column('members', 'longest_weekly_streak')
    op.drop_column('members', 'current_weekly_streak')
    # ### end Alembic commands ###
