"""add retired_tags table

Revision ID: 9874e76d1861
Revises: c3f1a4e6b2d7
Create Date: 2026-09-13 03:37:04.660447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9874e76d1861'
down_revision = 'c3f1a4e6b2d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retired_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retired_tags_member_id'), 'retired_tags', ['member_id'], unique=False)
    op.create_index(op.f('ix_retired_tags_tag_id'), 'retired_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retired_tags_tag_id'), table_name='retired_tags')
    op.drop_index(op.f('ix_retired_tags_member_id'), table_name='retired_tags')
    op.drop_table('retired_tags')
    # ### end Alembic commands ###
