"""add xp leveling fields

Revision ID: 9d8625f4163e
Revises: df0be6b9e9b0
Create Date: 2026-09-09 20:18:47.453824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d8625f4163e'
down_revision = 'df0be6b9e9b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('xp', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('members', sa.Column('level', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('members', sa.Column('lifetime_xp', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('members', sa.Column('prestige_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'prestige_count')
    op.drop_column('members', 'lifetime_xp')
    op.drop_column('members', 'level')
    op.drop_column('members', 'xp')
    # ### end Alembic commands ###
