"""add visits table and tap direction

Revision ID: d21d79246ce7
Revises: 9d8625f4163e
Create Date: 2026-09-10 04:23:53.051571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd21d79246ce7'
down_revision = '9d8625f4163e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_in_reader_id', sa.String(), nullable=False),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_reader_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_member_id'), 'visits', ['member_id'], unique=False)
    op.add_column('taps', sa.Column('direction', sa.String(), nullable=False, server_default='in'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taps', 'direction')
    op.drop_index(op.f('ix_visits_member_id'), table_name='visits')
    op.drop_table('visits')
    # ### end Alembic commands ###
